export const artStyle = [
  {
    name: "常用风格",
    styles: [
      {
        catName: "常用风格",
        name: "2D动漫风格",
        prompt: "(画风：2D动漫风格,2d animation style)",
        promptEn: "2d animation style",
        fileUrl: "https://files.manjuwu.cn/anime/aigc/g/i/68985098-60f1-4b64-b973-64071d95edb3.png",
      },
      {
        catName: "常用风格",
        name: "真人写实",
        prompt: "(画风：照片级真人超写实,photorealistic, lifelike, ultra detailed)",
        promptEn: "photorealistic, lifelike, ultra detailed",
        fileUrl: "https://files.manjuwu.cn/anime/uploads/other/20260127/025c131413394fb5a9214e00d67ea354.jpg",
      },
      {
        catName: "常用风格",
        name: "3D国创",
        prompt: "(画风：3D国创,Chinese 3D animation style)",
        promptEn: "Chinese 3D animation style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/3D国创.webp",
      },
      {
        catName: "常用风格",
        name: "三渲二",
        prompt: "(画风：三渲二,cel-shaded)",
        promptEn: "cel-shaded",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/三渲二.webp",
      },
      {
        catName: "常用风格",
        name: "日式少女漫",
        prompt: "(画风：日式少女漫,shoujo manga style)",
        promptEn: "shoujo manga style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/日式少女漫.webp",
      },
      {
        catName: "常用风格",
        name: "龙族传说",
        prompt: "(画风：龙族传说,dragon clan legend art)",
        promptEn: "dragon clan legend art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/龙族传说.webp",
      },
      {
        catName: "常用风格",
        name: "吉卜力",
        prompt: "(画风：吉卜力,Ghibli style, Studio Ghibli aesthetic)",
        promptEn: "Ghibli style, Studio Ghibli aesthetic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/吉卜力.webp",
      },
      {
        catName: "常用风格",
        name: "80s年代",
        prompt: "(画风：80s年代,1980s retro)",
        promptEn: "1980s retro",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/80s年代.webp",
      },
      {
        catName: "常用风格",
        name: "木叶村",
        prompt: "(画风：木叶村,Naruto style, Konohagakure)",
        promptEn: "Naruto style, Konohagakure",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/木叶村.webp",
      },
      {
        catName: "常用风格",
        name: "名侦探阿楠",
        prompt: "(画风：名侦探阿楠,Detective Conan style, Case Closed style)",
        promptEn: "Detective Conan style, Case Closed style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/名侦探阿楠.webp",
      },
      {
        catName: "常用风格",
        name: "草帽团",
        prompt: "(画风：草帽团,One Piece style, Straw Hat Pirates)",
        promptEn: "One Piece style, Straw Hat Pirates",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/草帽团.webp",
      },
      {
        catName: "常用风格",
        name: "奇幻平涂",
        prompt: "(画风：奇幻平涂,fantasy flat illustration)",
        promptEn: "fantasy flat illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/奇幻平涂.webp",
      },
      {
        catName: "常用风格",
        name: "藤本树",
        prompt: "(画风：藤本树,Tatsuki Fujimoto style)",
        promptEn: "Tatsuki Fujimoto style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/藤本树.webp",
      },
      {
        catName: "常用风格",
        name: "空灵哥特",
        prompt: "(画风：空灵哥特,ethereal gothic)",
        promptEn: "ethereal gothic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/空灵哥特.webp",
      },
      {
        catName: "常用风格",
        name: "美式3D",
        prompt: "(画风：美式3D,American 3D animation style/ Pixar style)",
        promptEn: "American 3D animation style/ Pixar style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/美式3D.webp",
      },
    ],
  },
  {
    name: "ip风格",
    styles: [
      {
        catName: "ip风格",
        name: "怪诞哥特卡通",
        prompt: "(画风：怪诞哥特卡通,grotesque gothic cartoon)",
        promptEn: "grotesque gothic cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/怪诞哥特卡通.webp",
      },
      {
        catName: "ip风格",
        name: "龙族传说",
        prompt: "(画风：龙族传说,dragon clan legend art)",
        promptEn: "dragon clan legend art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/龙族传说.webp",
      },
      {
        catName: "ip风格",
        name: "比奇堡",
        prompt: "(画风：比奇堡,SpongeBob SquarePants style, Bikini Bottom)",
        promptEn: "SpongeBob SquarePants style, Bikini Bottom",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/比奇堡.webp",
      },
      {
        catName: "ip风格",
        name: "吉卜力",
        prompt: "(画风：吉卜力,Ghibli style, Studio Ghibli aesthetic)",
        promptEn: "Ghibli style, Studio Ghibli aesthetic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/吉卜力.webp",
      },
      {
        catName: "ip风格",
        name: "复古掌机",
        prompt: "(画风：复古掌机,retro pixel art, 8-bit graphics)",
        promptEn: "retro pixel art, 8-bit graphics",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/复古掌机.webp",
      },
      {
        catName: "ip风格",
        name: "美式喜剧",
        prompt: "(画风：美式喜剧,American sitcom aesthetic)",
        promptEn: "American sitcom aesthetic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/美式喜剧.webp",
      },
      {
        catName: "ip风格",
        name: "三渲二",
        prompt: "(画风：三渲二,cel-shaded)",
        promptEn: "cel-shaded",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/三渲二.webp",
      },
      {
        catName: "ip风格",
        name: "史努比",
        prompt: "(画风：史努比,Peanuts comic style)",
        promptEn: "Peanuts comic style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/史努比.webp",
      },
      {
        catName: "ip风格",
        name: "锈湖",
        prompt: "(画风：锈湖,Rusty Lake game style)",
        promptEn: "Rusty Lake game style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/锈湖.webp",
      },
      {
        catName: "ip风格",
        name: "名侦探阿楠",
        prompt: "(画风：名侦探阿楠,Detective Conan style, Case Closed style)",
        promptEn: "Detective Conan style, Case Closed style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/名侦探阿楠.webp",
      },
      {
        catName: "ip风格",
        name: "草帽团",
        prompt: "(画风：草帽团,One Piece style, Straw Hat Pirates)",
        promptEn: "One Piece style, Straw Hat Pirates",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/草帽团.webp",
      },
      {
        catName: "ip风格",
        name: "乐高",
        prompt: "(画风：乐高,LEGO style, brick-built)",
        promptEn: "LEGO style, brick-built",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/乐高.webp",
      },
      {
        catName: "ip风格",
        name: "动森",
        prompt: "(画风：动森,Animal Crossing style)",
        promptEn: "Animal Crossing style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/动森.webp",
      },
      {
        catName: "ip风格",
        name: "蜡笔小新",
        prompt: "(画风：蜡笔小新,Crayon Shin-chan style)",
        promptEn: "Crayon Shin-chan style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/蜡笔小新.webp",
      },
      {
        catName: "ip风格",
        name: "扁平图形设计",
        prompt: "(画风：扁平图形设计,flat design, minimal vector art)",
        promptEn: "flat design, minimal vector art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/扁平图形设计.webp",
      },
      {
        catName: "ip风格",
        name: "莱卡定格动画",
        prompt: "(画风：莱卡定格动画,Laika stop-motion style)",
        promptEn: "Laika stop-motion style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/莱卡定格动画.webp",
      },
      {
        catName: "ip风格",
        name: "日本小人",
        prompt: "(画风：日本小人,chibi)",
        promptEn: "chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/ip风格/日本小人.webp",
      },
    ],
  },
  {
    name: "插画风格",
    styles: [
      {
        catName: "插画风格",
        name: "生动水彩图形",
        prompt: "(画风：生动水彩图形,vibrant watercolor illustration)",
        promptEn: "vibrant watercolor illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/生动水彩图形.webp",
      },
      {
        catName: "插画风格",
        name: "单色排线素描",
        prompt: "(画风：单色排线素描,monochrome cross-hatching sketch)",
        promptEn: "monochrome cross-hatching sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/单色排线素描.webp",
      },
      {
        catName: "插画风格",
        name: "怪诞哥特卡通",
        prompt: "(画风：怪诞哥特卡通,grotesque gothic cartoon)",
        promptEn: "grotesque gothic cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/怪诞哥特卡通.webp",
      },
      {
        catName: "插画风格",
        name: "彩铅素描插画",
        prompt: "(画风：彩铅素描插画,colored pencil sketch)",
        promptEn: "colored pencil sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/彩铅素描插画.webp",
      },
      {
        catName: "插画风格",
        name: "经典美式漫画",
        prompt: "(画风：经典美式漫画,classic American comic book style)",
        promptEn: "classic American comic book style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/经典美式漫画.webp",
      },
      {
        catName: "插画风格",
        name: "诡萌幻想绘本",
        prompt: "(画风：诡萌幻想绘本,Q Cute Mark Pen Coloring)",
        promptEn: "Q Cute Mark Pen Coloring",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/诡萌幻想绘本.webp",
      },
      {
        catName: "插画风格",
        name: "波普印刷",
        prompt: "(画风：波普印刷,pop art print)",
        promptEn: "pop art print",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/波普印刷.webp",
      },
      {
        catName: "插画风格",
        name: "涂色颗粒怀旧",
        prompt: "(画风：涂色颗粒怀旧,Legend of the Dragon Clan)",
        promptEn: "Legend of the Dragon Clan",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/涂色颗粒怀旧.webp",
      },
      {
        catName: "插画风格",
        name: "Q萌马克笔着色",
        prompt: "(画风：Q萌马克笔着色,chibi marker art)",
        promptEn: "chibi marker art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/Q萌马克笔着色.webp",
      },
      {
        catName: "插画风格",
        name: "蚀刻光影",
        prompt: "(画风：蚀刻光影,etching with dramatic lighting)",
        promptEn: "etching with dramatic lighting",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/蚀刻光影.webp",
      },
      {
        catName: "插画风格",
        name: "复古梦幻赛璐璐",
        prompt: "(画风：复古梦幻赛璐璐,retro dreamlike cel animation)",
        promptEn: "retro dreamlike cel animation",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/复古梦幻赛璐璐.webp",
      },
      {
        catName: "插画风格",
        name: "比奇堡",
        prompt: "(画风：比奇堡,SpongeBob SquarePants style, Bikini Bottom)",
        promptEn: "SpongeBob SquarePants style, Bikini Bottom",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/比奇堡.webp",
      },
      {
        catName: "插画风格",
        name: "彩色排线手绘",
        prompt: "(画风：彩色排线手绘,colorful cross-hatching, hand-drawn)",
        promptEn: "colorful cross-hatching, hand-drawn",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/彩色排线手绘.webp",
      },
      {
        catName: "插画风格",
        name: "复古线条都市",
        prompt: "(画风：复古线条都市,retro line art urban)",
        promptEn: "retro line art urban",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/复古线条都市.webp",
      },
      {
        catName: "插画风格",
        name: "浮世绘超现实",
        prompt: "(画风：浮世绘超现实,surreal ukiyo-e)",
        promptEn: "surreal ukiyo-e",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/浮世绘超现实.webp",
      },
      {
        catName: "插画风格",
        name: "冷静感线条",
        prompt: "(画风：冷静感线条,clean calm line art)",
        promptEn: "clean calm line art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/冷静感线条.webp",
      },
      {
        catName: "插画风格",
        name: "复杂线条都市漫",
        prompt: "(画风：复杂线条都市漫,intricate line art urban comic)",
        promptEn: "intricate line art urban comic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/复杂线条都市漫.webp",
      },
      {
        catName: "插画风格",
        name: "通透光泽马卡龙",
        prompt: "(画风：通透光泽马卡龙,glossy translucent macaron colors)",
        promptEn: "glossy translucent macaron colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/通透光泽马卡龙.webp",
      },
      {
        catName: "插画风格",
        name: "魅惑哥特霓虹",
        prompt: "(画风：魅惑哥特霓虹,alluring gothic neon)",
        promptEn: "alluring gothic neon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/魅惑哥特霓虹.webp",
      },
      {
        catName: "插画风格",
        name: "表现主义儿童",
        prompt: "(画风：表现主义儿童,expressionist child art)",
        promptEn: "expressionist child art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/表现主义儿童.webp",
      },
      {
        catName: "插画风格",
        name: "粘土玩具",
        prompt: "(画风：粘土玩具,clay toy, claymation style)",
        promptEn: "clay toy, claymation style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/粘土玩具.webp",
      },
      {
        catName: "插画风格",
        name: "吉卜力",
        prompt: "(画风：吉卜力,Ghibli style, Studio Ghibli aesthetic)",
        promptEn: "Ghibli style, Studio Ghibli aesthetic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/吉卜力.webp",
      },
      {
        catName: "插画风格",
        name: "童趣蜡笔插画",
        prompt: "(画风：童趣蜡笔插画,childlike crayon illustration)",
        promptEn: "childlike crayon illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/童趣蜡笔插画.webp",
      },
      {
        catName: "插画风格",
        name: "怀旧胶片线条",
        prompt: "(画风：怀旧胶片线条,nostalgic film grain line art)",
        promptEn: "nostalgic film grain line art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/怀旧胶片线条.webp",
      },
      {
        catName: "插画风格",
        name: "唯美清新通透",
        prompt: "(画风：唯美清新通透,aesthetic fresh translucent)",
        promptEn: "aesthetic fresh translucent",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/唯美清新通透.webp",
      },
      {
        catName: "插画风格",
        name: "哥特都市涂鸦",
        prompt: "(画风：哥特都市涂鸦,gothic urban graffiti)",
        promptEn: "gothic urban graffiti",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/哥特都市涂鸦.webp",
      },
      {
        catName: "插画风格",
        name: "高能动感卡通",
        prompt: "(画风：高能动感卡通,high-energy dynamic cartoon)",
        promptEn: "high-energy dynamic cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/高能动感卡通.webp",
      },
      {
        catName: "插画风格",
        name: "梦幻线条怪诞",
        prompt: "(画风：梦幻线条怪诞,dreamlike grotesque line art)",
        promptEn: "dreamlike grotesque line art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/梦幻线条怪诞.webp",
      },
      {
        catName: "插画风格",
        name: "轻复古水彩",
        prompt: "(画风：轻复古水彩,Prism malfunction art)",
        promptEn: "Prism malfunction art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/轻复古水彩.webp",
      },
      {
        catName: "插画风格",
        name: "美式肌肉讽刺",
        prompt: "(画风：美式肌肉讽刺,American muscle satire)",
        promptEn: "American muscle satire",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/美式肌肉讽刺.webp",
      },
      {
        catName: "插画风格",
        name: "潮流都市",
        prompt: "(画风：潮流都市,urban streetwear aesthetic)",
        promptEn: "urban streetwear aesthetic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/潮流都市.webp",
      },
      {
        catName: "插画风格",
        name: "奶油色绘本",
        prompt: "(画风：奶油色绘本,cream-colored picture book)",
        promptEn: "cream-colored picture book",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/奶油色绘本.webp",
      },
      {
        catName: "插画风格",
        name: "棱镜故障艺术",
        prompt: "(画风：棱镜故障艺术,prism glitch art)",
        promptEn: "prism glitch art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/棱镜故障艺术.webp",
      },
      {
        catName: "插画风格",
        name: "朦胧暖色速写",
        prompt: "(画风：朦胧暖色速写,hazy warm-toned sketch)",
        promptEn: "hazy warm-toned sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/朦胧暖色速写.webp",
      },
      {
        catName: "插画风格",
        name: "怀旧电影感氛围",
        prompt: "(画风：怀旧电影感氛围,nostalgic cinematic atmosphere)",
        promptEn: "nostalgic cinematic atmosphere",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/怀旧电影感氛围.webp",
      },
      {
        catName: "插画风格",
        name: "欧漫概念艺术",
        prompt: "(画风：欧漫概念艺术,European comic concept art)",
        promptEn: "European comic concept art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/欧漫概念艺术.webp",
      },
      {
        catName: "插画风格",
        name: "抒情柔光线条",
        prompt: "(画风：抒情柔光线条,lyrical soft-glow line art)",
        promptEn: "lyrical soft-glow line art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/抒情柔光线条.webp",
      },
      {
        catName: "插画风格",
        name: "怪萌墨线",
        prompt: "(画风：怪萌墨线,weird-cute ink lines)",
        promptEn: "weird-cute ink lines",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/怪萌墨线.webp",
      },
      {
        catName: "插画风格",
        name: "硬边萌系赛璐璐",
        prompt: "(画风：硬边萌系赛璐璐,hard-edged cute cel animation)",
        promptEn: "hard-edged cute cel animation",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/硬边萌系赛璐璐.webp",
      },
      {
        catName: "插画风格",
        name: "柔光浪漫水彩",
        prompt: "(画风：柔光浪漫水彩,soft romantic watercolor)",
        promptEn: "soft romantic watercolor",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/柔光浪漫水彩.webp",
      },
      {
        catName: "插画风格",
        name: "油画釉光",
        prompt: "(画风：油画釉光,oil painting with glaze finish)",
        promptEn: "oil painting with glaze finish",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/油画釉光.webp",
      },
      {
        catName: "插画风格",
        name: "粗犷墨线",
        prompt: "(画风：粗犷墨线,rough ink lines)",
        promptEn: "rough ink lines",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/粗犷墨线.webp",
      },
      {
        catName: "插画风格",
        name: "五零年代",
        prompt: "(画风：五零年代,1950s style)",
        promptEn: "1950s style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/五零年代.webp",
      },
      {
        catName: "插画风格",
        name: "古典戏剧情绪",
        prompt: "(画风：古典戏剧情绪,classical dramatic mood)",
        promptEn: "classical dramatic mood",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/古典戏剧情绪.webp",
      },
      {
        catName: "插画风格",
        name: "治愈童趣颗粒",
        prompt: "(画风：治愈童趣颗粒,healing childish grain texture)",
        promptEn: "healing childish grain texture",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/治愈童趣颗粒.webp",
      },
      {
        catName: "插画风格",
        name: "墨线卡通",
        prompt: "(画风：墨线卡通,ink line cartoon)",
        promptEn: "ink line cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/墨线卡通.webp",
      },
      {
        catName: "插画风格",
        name: "温馨彩绘",
        prompt: "(画风：温馨彩绘,cozy painted illustration)",
        promptEn: "cozy painted illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/温馨彩绘.webp",
      },
      {
        catName: "插画风格",
        name: "美式粗线漫画",
        prompt: "(画风：美式粗线漫画,American bold line comic)",
        promptEn: "American bold line comic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/美式粗线漫画.webp",
      },
      {
        catName: "插画风格",
        name: "发光线条柔光",
        prompt: "(画风：发光线条柔光,glowing line art with soft light)",
        promptEn: "glowing line art with soft light",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/发光线条柔光.webp",
      },
      {
        catName: "插画风格",
        name: "通透柔光厚涂",
        prompt: "(画风：通透柔光厚涂,translucent soft glow, thick paint)",
        promptEn: "translucent soft glow, thick paint",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/通透柔光厚涂.webp",
      },
      {
        catName: "插画风格",
        name: "通透光影厚涂",
        prompt: "(画风：通透光影厚涂,translucent lighting, thick paint)",
        promptEn: "translucent lighting, thick paint",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/通透光影厚涂.webp",
      },
      {
        catName: "插画风格",
        name: "光影平涂",
        prompt: "(画风：光影平涂,flat shading with lighting)",
        promptEn: "flat shading with lighting",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/光影平涂.webp",
      },
      {
        catName: "插画风格",
        name: "粗糙颗粒肌理",
        prompt: "(画风：粗糙颗粒肌理,rough granular texture)",
        promptEn: "rough granular texture",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/粗糙颗粒肌理.webp",
      },
      {
        catName: "插画风格",
        name: "粗线快面卡通",
        prompt: "(画风：粗线快面卡通,bold shape fast-paced cartoon)",
        promptEn: "bold shape fast-paced cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/粗线快面卡通.webp",
      },
      {
        catName: "插画风格",
        name: "卡通平涂漫画",
        prompt: "(画风：卡通平涂漫画,cel-shaded flat comic)",
        promptEn: "cel-shaded flat comic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/卡通平涂漫画.webp",
      },
      {
        catName: "插画风格",
        name: "柔光平涂",
        prompt: "(画风：柔光平涂,soft glow flat colors)",
        promptEn: "soft glow flat colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/柔光平涂.webp",
      },
      {
        catName: "插画风格",
        name: "Q版草绘",
        prompt: "(画风：Q版草绘,chibi rough sketch)",
        promptEn: "chibi rough sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/Q版草绘.webp",
      },
      {
        catName: "插画风格",
        name: "清新水彩墨线",
        prompt: "(画风：清新水彩墨线,fresh watercolor with ink lines)",
        promptEn: "fresh watercolor with ink lines",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/清新水彩墨线.webp",
      },
      {
        catName: "插画风格",
        name: "治愈冒险漫画",
        prompt: "(画风：治愈冒险漫画,healing adventure comic)",
        promptEn: "healing adventure comic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/治愈冒险漫画.webp",
      },
      {
        catName: "插画风格",
        name: "邪魅琉璃",
        prompt: "(画风：邪魅琉璃,eerie luminous glass)",
        promptEn: "eerie luminous glass",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/邪魅琉璃.webp",
      },
      {
        catName: "插画风格",
        name: "风格化撞色赛博",
        prompt: "(画风：风格化撞色赛博,stylized cyberpunk with clashing colors)",
        promptEn: "stylized cyberpunk with clashing colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/风格化撞色赛博.webp",
      },
      {
        catName: "插画风格",
        name: "虹彩梦幻治愈",
        prompt: "(画风：虹彩梦幻治愈,iridescent dreamy healing)",
        promptEn: "iridescent dreamy healing",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/虹彩梦幻治愈.webp",
      },
      {
        catName: "插画风格",
        name: "治愈柔和Q版",
        prompt: "(画风：治愈柔和Q版,healing soft chibi)",
        promptEn: "healing soft chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/治愈柔和Q版.webp",
      },
      {
        catName: "插画风格",
        name: "唯美柔光辐射",
        prompt: "(画风：唯美柔光辐射,aesthetic soft glow radiance)",
        promptEn: "aesthetic soft glow radiance",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/唯美柔光辐射.webp",
      },
      {
        catName: "插画风格",
        name: "质朴蜡笔",
        prompt: "(画风：质朴蜡笔,textured crayon drawing)",
        promptEn: "textured crayon drawing",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/质朴蜡笔.webp",
      },
      {
        catName: "插画风格",
        name: "戏剧光影水彩",
        prompt: "(画风：戏剧光影水彩,dramatic watercolor with lighting)",
        promptEn: "dramatic watercolor with lighting",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/戏剧光影水彩.webp",
      },
      {
        catName: "插画风格",
        name: "柔光原画厚涂",
        prompt: "(画风：柔光原画厚涂,key visual style, soft glow, thick paint)",
        promptEn: "key visual style, soft glow, thick paint",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/柔光原画厚涂.webp",
      },
      {
        catName: "插画风格",
        name: "粗犷硬边赛璐璐",
        prompt: "(画风：粗犷硬边赛璐璐,rugged hard-edged cel animation)",
        promptEn: "rugged hard-edged cel animation",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/粗犷硬边赛璐璐.webp",
      },
      {
        catName: "插画风格",
        name: "低饱和平涂手绘",
        prompt: "(画风：低饱和平涂手绘,low saturation flat illustration)",
        promptEn: "low saturation flat illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/低饱和平涂手绘.webp",
      },
      {
        catName: "插画风格",
        name: "可爱马卡龙",
        prompt: "(画风：可爱马卡龙,cute macaron colors)",
        promptEn: "cute macaron colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/可爱马卡龙.webp",
      },
      {
        catName: "插画风格",
        name: "柔光影厚涂",
        prompt: "(画风：柔光影厚涂,soft light and shadow, thick paint)",
        promptEn: "soft light and shadow, thick paint",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/柔光影厚涂.webp",
      },
      {
        catName: "插画风格",
        name: "迷幻复古都市",
        prompt: "(画风：迷幻复古都市,psychedelic retro city)",
        promptEn: "psychedelic retro city",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/迷幻复古都市.webp",
      },
      {
        catName: "插画风格",
        name: "颗粒粉彩童话风",
        prompt: "(画风：颗粒粉彩童话风,grainy pastel fairy tale)",
        promptEn: "grainy pastel fairy tale",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/颗粒粉彩童话风.webp",
      },
      {
        catName: "插画风格",
        name: "高对比应边缘",
        prompt: "(画风：高对比应边缘,Warm Healing Q Edition)",
        promptEn: "Warm Healing Q Edition",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/高对比应边缘.webp",
      },
      {
        catName: "插画风格",
        name: "粗线活力动感",
        prompt: "(画风：粗线活力动感,bold line vibrant motion)",
        promptEn: "bold line vibrant motion",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/粗线活力动感.webp",
      },
      {
        catName: "插画风格",
        name: "猛烈印象派",
        prompt: "(画风：猛烈印象派,fierce impressionism)",
        promptEn: "fierce impressionism",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/猛烈印象派.webp",
      },
      {
        catName: "插画风格",
        name: "温暖治愈Q版",
        prompt: "(画风：温暖治愈Q版,warm healing chibi)",
        promptEn: "warm healing chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/温暖治愈Q版.webp",
      },
      {
        catName: "插画风格",
        name: "莫兰迪水粉手绘",
        prompt: "(画风：莫兰迪水粉手绘,Morandi style gouache painting)",
        promptEn: "Morandi style gouache painting",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/莫兰迪水粉手绘.webp",
      },
      {
        catName: "插画风格",
        name: "空气彩铅",
        prompt: "(画风：空气彩铅,airy colored pencil)",
        promptEn: "airy colored pencil",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/空气彩铅.webp",
      },
      {
        catName: "插画风格",
        name: "东方淡彩",
        prompt: "(画风：东方淡彩,eastern light color wash)",
        promptEn: "eastern light color wash",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/东方淡彩.webp",
      },
      {
        catName: "插画风格",
        name: "都市潮漫硬边",
        prompt: "(画风：都市潮漫硬边,urban trendy comic with hard edges)",
        promptEn: "urban trendy comic with hard edges",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/都市潮漫硬边.webp",
      },
      {
        catName: "插画风格",
        name: "粗线潮流Q版",
        prompt: "(画风：粗线潮流Q版,bold line trendy chibi)",
        promptEn: "bold line trendy chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/粗线潮流Q版.webp",
      },
      {
        catName: "插画风格",
        name: "甜美可爱复古",
        prompt: "(画风：甜美可爱复古,sweet kawaii retro)",
        promptEn: "sweet kawaii retro",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/甜美可爱复古.webp",
      },
      {
        catName: "插画风格",
        name: "炭笔暗黑朋克",
        prompt: "(画风：炭笔暗黑朋克,charcoal dark punk)",
        promptEn: "charcoal dark punk",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/炭笔暗黑朋克.webp",
      },
      {
        catName: "插画风格",
        name: "复古褪色速写",
        prompt: "(画风：复古褪色速写,faded vintage sketch)",
        promptEn: "faded vintage sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/复古褪色速写.webp",
      },
      {
        catName: "插画风格",
        name: "韩式漫画厚涂",
        prompt: "(画风：韩式漫画厚涂,Korean webtoon style, thick paint)",
        promptEn: "Korean webtoon style, thick paint",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/韩式漫画厚涂.webp",
      },
      {
        catName: "插画风格",
        name: "可爱抽象涂鸦",
        prompt: "(画风：可爱抽象涂鸦,cute abstract doodle)",
        promptEn: "cute abstract doodle",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/可爱抽象涂鸦.webp",
      },
      {
        catName: "插画风格",
        name: "复古赛露露怀旧",
        prompt: "(画风：复古赛露露怀旧,American style granules)",
        promptEn: "American style granules",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/复古赛露露怀旧.webp",
      },
      {
        catName: "插画风格",
        name: "蒸汽波神话糖",
        prompt: "(画风：蒸汽波神话糖,vaporwave myth candy)",
        promptEn: "vaporwave myth candy",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/蒸汽波神话糖.webp",
      },
      {
        catName: "插画风格",
        name: "美式颗粒",
        prompt: "(画风：美式颗粒,American comic halftone dots)",
        promptEn: "American comic halftone dots",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/美式颗粒.webp",
      },
      {
        catName: "插画风格",
        name: "厚涂柔光怀旧",
        prompt: "(画风：厚涂柔光怀旧,thick paint, soft glow, nostalgic)",
        promptEn: "thick paint, soft glow, nostalgic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/厚涂柔光怀旧.webp",
      },
      {
        catName: "插画风格",
        name: "扁平涂鸦",
        prompt: "(画风：扁平涂鸦,flat doodle style)",
        promptEn: "flat doodle style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/扁平涂鸦.webp",
      },
      {
        catName: "插画风格",
        name: "甜美粉彩",
        prompt: "(画风：甜美粉彩,sweet pastel)",
        promptEn: "sweet pastel",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/甜美粉彩.webp",
      },
      {
        catName: "插画风格",
        name: "极简色块复古",
        prompt: "(画风：极简色块复古,Minimalist color block retro)",
        promptEn: "Minimalist color block retro",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/极简色块复古.webp",
      },
      {
        catName: "插画风格",
        name: "童趣速写",
        prompt: "(画风：童趣速写,childlike sketch)",
        promptEn: "childlike sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/童趣速写.webp",
      },
      {
        catName: "插画风格",
        name: "水粉童书插画",
        prompt: "(画风：水粉童书插画,gouache children's book illustration)",
        promptEn: "gouache children's book illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/水粉童书插画.webp",
      },
      {
        catName: "插画风格",
        name: "简约扁平手绘",
        prompt: "(画风：简约扁平手绘,Minimally flat hand drawn)",
        promptEn: "Minimally flat hand drawn",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/简约扁平手绘.webp",
      },
      {
        catName: "插画风格",
        name: "活力萌系赛璐璐",
        prompt: "(画风：活力萌系赛璐璐,vibrant cute cel animation)",
        promptEn: "vibrant cute cel animation",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/活力萌系赛璐璐.webp",
      },
      {
        catName: "插画风格",
        name: "治愈Q萌",
        prompt: "(画风：治愈Q萌,healing chibi)",
        promptEn: "healing chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/治愈Q萌.webp",
      },
      {
        catName: "插画风格",
        name: "矢量扁平色块",
        prompt: "(画风：矢量扁平色块,vector flat colors)",
        promptEn: "vector flat colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/矢量扁平色块.webp",
      },
      {
        catName: "插画风格",
        name: "清新童趣Q版",
        prompt: "(画风：清新童趣Q版,fresh childish chibi)",
        promptEn: "fresh childish chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/插画风格/清新童趣Q版.webp",
      },
    ],
  },
  {
    name: "可爱Q版",
    styles: [
      {
        catName: "可爱Q版",
        name: "Q萌马克笔着色",
        prompt: "(画风：Q萌马克笔着色,chibi marker art)",
        promptEn: "chibi marker art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/Q萌马克笔着色.webp",
      },
      {
        catName: "可爱Q版",
        name: "比奇堡",
        prompt: "(画风：比奇堡,SpongeBob SquarePants style, Bikini Bottom)",
        promptEn: "SpongeBob SquarePants style, Bikini Bottom",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/比奇堡.webp",
      },
      {
        catName: "可爱Q版",
        name: "彩色排线手绘",
        prompt: "(画风：彩色排线手绘,colorful cross-hatching, hand-drawn)",
        promptEn: "colorful cross-hatching, hand-drawn",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/彩色排线手绘.webp",
      },
      {
        catName: "可爱Q版",
        name: "复古线条都市",
        prompt: "(画风：复古线条都市,retro line art urban)",
        promptEn: "retro line art urban",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/复古线条都市.webp",
      },
      {
        catName: "可爱Q版",
        name: "通透光泽马卡龙",
        prompt: "(画风：通透光泽马卡龙,glossy translucent macaron colors)",
        promptEn: "glossy translucent macaron colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/通透光泽马卡龙.webp",
      },
      {
        catName: "可爱Q版",
        name: "童趣蜡笔插画",
        prompt: "(画风：童趣蜡笔插画,childlike crayon illustration)",
        promptEn: "childlike crayon illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/童趣蜡笔插画.webp",
      },
      {
        catName: "可爱Q版",
        name: "高能动感卡通",
        prompt: "(画风：高能动感卡通,high-energy dynamic cartoon)",
        promptEn: "high-energy dynamic cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/高能动感卡通.webp",
      },
      {
        catName: "可爱Q版",
        name: "梦幻线条怪诞",
        prompt: "(画风：梦幻线条怪诞,dreamlike grotesque line art)",
        promptEn: "dreamlike grotesque line art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/梦幻线条怪诞.webp",
      },
      {
        catName: "可爱Q版",
        name: "火柴人",
        prompt: "(画风：火柴人,stick figure)",
        promptEn: "stick figure",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/火柴人.webp",
      },
      {
        catName: "可爱Q版",
        name: "朦胧暖色速写",
        prompt: "(画风：朦胧暖色速写,hazy warm-toned sketch)",
        promptEn: "hazy warm-toned sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/朦胧暖色速写.webp",
      },
      {
        catName: "可爱Q版",
        name: "复古彩光",
        prompt: "(画风：复古彩光,vintage chromatic glow)",
        promptEn: "vintage chromatic glow",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/复古彩光.webp",
      },
      {
        catName: "可爱Q版",
        name: "粗线超级Q版",
        prompt: "(画风：粗线超级Q版,bold line super deformed)",
        promptEn: "bold line super deformed",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/粗线超级Q版.webp",
      },
      {
        catName: "可爱Q版",
        name: "墨线卡通",
        prompt: "(画风：墨线卡通,ink line cartoon)",
        promptEn: "ink line cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/墨线卡通.webp",
      },
      {
        catName: "可爱Q版",
        name: "Q版3D",
        prompt: "(画风：Q版3D,3D chibi)",
        promptEn: "3D chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/Q版3D.webp",
      },
      {
        catName: "可爱Q版",
        name: "美式粗线漫画",
        prompt: "(画风：美式粗线漫画,American bold line comic)",
        promptEn: "American bold line comic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/美式粗线漫画.webp",
      },
      {
        catName: "可爱Q版",
        name: "莫兰蒂Q版",
        prompt: "(画风：莫兰蒂Q版,Rough granular texture)",
        promptEn: "Rough granular texture",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/莫兰蒂Q版.webp",
      },
      {
        catName: "可爱Q版",
        name: "粗线块卡通",
        prompt: "(画风：粗线块卡通,bold shape cartoon)",
        promptEn: "bold shape cartoon",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/粗线块卡通.webp",
      },
      {
        catName: "可爱Q版",
        name: "Q版草绘",
        prompt: "(画风：Q版草绘,chibi rough sketch)",
        promptEn: "chibi rough sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/Q版草绘.webp",
      },
      {
        catName: "可爱Q版",
        name: "治愈冒险漫画",
        prompt: "(画风：治愈冒险漫画,healing adventure comic)",
        promptEn: "healing adventure comic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/治愈冒险漫画.webp",
      },
      {
        catName: "可爱Q版",
        name: "治愈柔和Q版",
        prompt: "(画风：治愈柔和Q版,healing soft chibi)",
        promptEn: "healing soft chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/治愈柔和Q版.webp",
      },
      {
        catName: "可爱Q版",
        name: "可爱马卡龙",
        prompt: "(画风：可爱马卡龙,cute macaron colors)",
        promptEn: "cute macaron colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/可爱马卡龙.webp",
      },
      {
        catName: "可爱Q版",
        name: "粗线活力动感",
        prompt: "(画风：粗线活力动感,bold line vibrant motion)",
        promptEn: "bold line vibrant motion",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/粗线活力动感.webp",
      },
      {
        catName: "可爱Q版",
        name: "温暖治愈Q版",
        prompt: "(画风：温暖治愈Q版,warm healing chibi)",
        promptEn: "warm healing chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/温暖治愈Q版.webp",
      },
      {
        catName: "可爱Q版",
        name: "毛绒玩具质感",
        prompt: "(画风：毛绒玩具质感,plush toy texture)",
        promptEn: "plush toy texture",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/毛绒玩具质感.webp",
      },
      {
        catName: "可爱Q版",
        name: "莫兰迪水粉手绘",
        prompt: "(画风：莫兰迪水粉手绘,Morandi style gouache painting)",
        promptEn: "Morandi style gouache painting",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/莫兰迪水粉手绘.webp",
      },
      {
        catName: "可爱Q版",
        name: "空气彩铅",
        prompt: "(画风：空气彩铅,airy colored pencil)",
        promptEn: "airy colored pencil",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/空气彩铅.webp",
      },
      {
        catName: "可爱Q版",
        name: "粗线潮流Q版",
        prompt: "(画风：粗线潮流Q版,bold line trendy chibi)",
        promptEn: "bold line trendy chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/粗线潮流Q版.webp",
      },
      {
        catName: "可爱Q版",
        name: "可爱抽象涂鸦",
        prompt: "(画风：可爱抽象涂鸦,cute abstract doodle)",
        promptEn: "cute abstract doodle",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/可爱抽象涂鸦.webp",
      },
      {
        catName: "可爱Q版",
        name: "美式颗粒",
        prompt: "(画风：美式颗粒,American comic halftone dots)",
        promptEn: "American comic halftone dots",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/美式颗粒.webp",
      },
      {
        catName: "可爱Q版",
        name: "甜美粉彩",
        prompt: "(画风：甜美粉彩,sweet pastel)",
        promptEn: "sweet pastel",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/甜美粉彩.webp",
      },
      {
        catName: "可爱Q版",
        name: "童趣速写",
        prompt: "(画风：童趣速写,childlike sketch)",
        promptEn: "childlike sketch",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/童趣速写.webp",
      },
      {
        catName: "可爱Q版",
        name: "像素",
        prompt: "(画风：像素,pixel art)",
        promptEn: "pixel art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/像素.webp",
      },
      {
        catName: "可爱Q版",
        name: "简约扁平手绘",
        prompt: "(画风：简约扁平手绘,Minimally flat hand drawn)",
        promptEn: "Minimally flat hand drawn",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/简约扁平手绘.webp",
      },
      {
        catName: "可爱Q版",
        name: "活力萌系赛璐璐",
        prompt: "(画风：活力萌系赛璐璐,vibrant cute cel animation)",
        promptEn: "vibrant cute cel animation",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/活力萌系赛璐璐.webp",
      },
      {
        catName: "可爱Q版",
        name: "蜡笔小新",
        prompt: "(画风：蜡笔小新,Crayon Shin-chan style)",
        promptEn: "Crayon Shin-chan style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/蜡笔小新.webp",
      },
      {
        catName: "可爱Q版",
        name: "极简几何艺术",
        prompt: "(画风：极简几何艺术,minimal geometric art)",
        promptEn: "minimal geometric art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/极简几何艺术.webp",
      },
      {
        catName: "可爱Q版",
        name: "扁平图形设计",
        prompt: "(画风：扁平图形设计,flat design, minimal vector art)",
        promptEn: "flat design, minimal vector art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/扁平图形设计.webp",
      },
      {
        catName: "可爱Q版",
        name: "矢量扁平色块",
        prompt: "(画风：矢量扁平色块,vector flat colors)",
        promptEn: "vector flat colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/矢量扁平色块.webp",
      },
      {
        catName: "可爱Q版",
        name: "清新童趣Q版",
        prompt: "(画风：清新童趣Q版,fresh childish chibi)",
        promptEn: "fresh childish chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/清新童趣Q版.webp",
      },
      {
        catName: "可爱Q版",
        name: "日本小人",
        prompt: "(画风：日本小人,chibi)",
        promptEn: "chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/可爱Q版/日本小人.webp",
      },
    ],
  },
  {
    name: "立体风格",
    styles: [
      {
        catName: "立体风格",
        name: "Q版3D",
        prompt: "(画风：Q版3D,3D chibi)",
        promptEn: "3D chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/Q版3D.webp",
      },
      {
        catName: "立体风格",
        name: "空灵现实",
        prompt: "(画风：空灵现实,ethereal realism)",
        promptEn: "ethereal realism",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/空灵现实.webp",
      },
      {
        catName: "立体风格",
        name: "方块世界",
        prompt: "(画风：方块世界,blocky world, voxel art)",
        promptEn: "blocky world, voxel art",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/方块世界.webp",
      },
      {
        catName: "立体风格",
        name: "毛绒玩具质感",
        prompt: "(画风：毛绒玩具质感,plush toy texture)",
        promptEn: "plush toy texture",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/毛绒玩具质感.webp",
      },
      {
        catName: "立体风格",
        name: "奇幻平涂",
        prompt: "(画风：奇幻平涂,fantasy flat illustration)",
        promptEn: "fantasy flat illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/奇幻平涂.webp",
      },
      {
        catName: "立体风格",
        name: "乐高",
        prompt: "(画风：乐高,LEGO style, brick-built)",
        promptEn: "LEGO style, brick-built",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/乐高.webp",
      },
      {
        catName: "立体风格",
        name: "折纸艺术",
        prompt: "(画风：折纸艺术,origami art style)",
        promptEn: "origami art style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/折纸艺术.webp",
      },
      {
        catName: "立体风格",
        name: "动森",
        prompt: "(画风：动森,Animal Crossing style)",
        promptEn: "Animal Crossing style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/动森.webp",
      },
      {
        catName: "立体风格",
        name: "美式3D",
        prompt: "(画风：美式3D,American 3D animation style/ Pixar style)",
        promptEn: "American 3D animation style/ Pixar style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/美式3D.webp",
      },
      {
        catName: "立体风格",
        name: "徕卡定格动画",
        prompt: "(画风：徕卡定格动画,Leica stop motion animation)",
        promptEn: "Leica stop motion animation",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/立体风格/徕卡定格动画.webp",
      },
    ],
  },
  {
    name: "日系风格",
    styles: [
      {
        catName: "日系风格",
        name: "日式少女漫",
        prompt: "(画风：日式少女漫,shoujo manga style)",
        promptEn: "shoujo manga style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/日式少女漫.webp",
      },
      {
        catName: "日系风格",
        name: "东方古典装饰",
        prompt: "(画风：东方古典装饰,eastern classical ornament)",
        promptEn: "eastern classical ornament",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/东方古典装饰.webp",
      },
      {
        catName: "日系风格",
        name: "复古梦幻赛璐璐",
        prompt: "(画风：复古梦幻赛璐璐,retro dreamlike cel animation)",
        promptEn: "retro dreamlike cel animation",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/复古梦幻赛璐璐.webp",
      },
      {
        catName: "日系风格",
        name: "复古日式",
        prompt: "(画风：复古日式,retro Japanese style)",
        promptEn: "retro Japanese style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/复古日式.webp",
      },
      {
        catName: "日系风格",
        name: "油画釉光",
        prompt: "(画风：油画釉光,oil painting with glaze finish)",
        promptEn: "oil painting with glaze finish",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/油画釉光.webp",
      },
      {
        catName: "日系风格",
        name: "80s年代",
        prompt: "(画风：80s年代,1980s retro)",
        promptEn: "1980s retro",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/80s年代.webp",
      },
      {
        catName: "日系风格",
        name: "柔光平涂",
        prompt: "(画风：柔光平涂,soft glow flat colors)",
        promptEn: "soft glow flat colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/柔光平涂.webp",
      },
      {
        catName: "日系风格",
        name: "低饱和平涂手绘",
        prompt: "(画风：低饱和平涂手绘,low saturation flat illustration)",
        promptEn: "low saturation flat illustration",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/低饱和平涂手绘.webp",
      },
      {
        catName: "日系风格",
        name: "可爱马卡龙",
        prompt: "(画风：可爱马卡龙,cute macaron colors)",
        promptEn: "cute macaron colors",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/可爱马卡龙.webp",
      },
      {
        catName: "日系风格",
        name: "空气彩铅",
        prompt: "(画风：空气彩铅,airy colored pencil)",
        promptEn: "airy colored pencil",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/空气彩铅.webp",
      },
      {
        catName: "日系风格",
        name: "蒸汽波神话糖",
        prompt: "(画风：蒸汽波神话糖,vaporwave myth candy)",
        promptEn: "vaporwave myth candy",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/蒸汽波神话糖.webp",
      },
      {
        catName: "日系风格",
        name: "藤本树",
        prompt: "(画风：藤本树,Tatsuki Fujimoto style)",
        promptEn: "Tatsuki Fujimoto style",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/藤本树.webp",
      },
      {
        catName: "日系风格",
        name: "空灵哥特",
        prompt: "(画风：空灵哥特,ethereal gothic)",
        promptEn: "ethereal gothic",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/空灵哥特.webp",
      },
      {
        catName: "日系风格",
        name: "日本小人",
        prompt: "(画风：日本小人,chibi)",
        promptEn: "chibi",
        fileUrl: "https://files.manjuwu.cn//app/FilmStyle/V1/日系风格/日本小人.webp",
      },
    ],
  },
];
